site_name: Auto File Exploration System
site_url: https://darenasc.github.io/auto-fes/

theme:
  name: "material"
  features:
    #   - navigation.tabs
    #   - navigation.sections
    # - toc.integrate
    #   - navigation.top
    - search.suggest
    #   - search.highlight
    #   - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

plugins:
  - search
  - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/darenasc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/darenasc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/darenasc/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  #   - admonition
  #   - pymdownx.arithmatex:
  #       generic: true
  #   - footnotes
  - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
#   - attr_list
copyright: |
  &copy; 2024 <a href="https://github.com/darenasc"  target="_blank" rel="noopener">Diego Arenas</a>
